# Generated by Django 4.2.7 on 2024-06-02 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0002_remove_user_user_grupp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='U_contrgrupp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.contrgrupp'),
            preserve_default=False,
        ),
    ]
