# Generated by Django 4.2.7 on 2024-06-02 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_u_contrgrupp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='U_contrgrupp',
        ),
    ]
