# Generated by Django 4.2.7 on 2024-06-02 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contrgrupp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Група контрагентів',
                'verbose_name_plural': 'Групи контрагентів',
                'db_table': 'contrgrupp',
            },
        ),
        migrations.CreateModel(
            name='Counterparts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Країна')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Місто')),
                ('street', models.CharField(blank=True, max_length=300, verbose_name='Вулиця')),
                ('number', models.CharField(blank=True, max_length=8, verbose_name='Номер будинку')),
                ('letter', models.CharField(blank=True, max_length=2, verbose_name='Дріб')),
                ('full_name', models.CharField(blank=True, max_length=800, verbose_name='Повна назва')),
                ('okpo_cod', models.CharField(blank=True, max_length=10, verbose_name='Код ЄДРПОУ')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ІПН')),
                ('director', models.CharField(blank=True, max_length=100, verbose_name='Керівник')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Телефон')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contrgrupp', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенти',
                'db_table': 'counterpart',
            },
        ),
    ]
