# Generated by Django 4.2.7 on 2024-06-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_u_g'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparts',
            name='guid',
            field=models.CharField(default=1, max_length=99, unique=True, verbose_name='guid'),
            preserve_default=False,
        ),
    ]
