# Generated by Django 4.2.7 on 2024-06-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_counterparts_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrgrupp',
            name='guid',
            field=models.CharField(default=1, max_length=99, unique=True, verbose_name='guid'),
            preserve_default=False,
        ),
    ]
