# Generated by Django 4.2.7 on 2024-06-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contrgrupp_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparts',
            name='adres',
            field=models.CharField(blank=True, max_length=800, verbose_name='Адреса'),
        ),
    ]
