# Generated by Django 4.2.7 on 2024-06-14 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_counterparts_adres'),
    ]

    operations = [
        migrations.CreateModel(
            name='licenss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=99, unique=True, verbose_name='guid')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('data_po', models.DateTimeField(auto_now_add=True, verbose_name='Ліцензія діє по')),
                ('contragent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contrgrupp', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Ліцензія',
                'verbose_name_plural': 'Ліцензії',
                'db_table': 'licenss',
            },
        ),
        migrations.DeleteModel(
            name='u_g',
        ),
    ]
