# Generated by Django 4.2.7 on 2024-06-14 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_licenss_delete_u_g'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrgrupp',
            name='pusers',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
