# Generated by Django 4.2.7 on 2024-06-14 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_contrgrupp_pusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrgrupp',
            name='pusers',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
