# Generated by Django 4.2.7 on 2024-06-15 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_contrgrupp_pusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenss',
            name='contragent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.counterparts', verbose_name='Контрагент'),
        ),
    ]
