# Generated by Django 4.2.7 on 2024-06-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_licenss_contragent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenss',
            name='data_po',
            field=models.DateTimeField(blank=True, verbose_name='Ліцензія діє по'),
        ),
    ]
