# Generated by Django 4.2.7 on 2024-06-17 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_alter_licenss_data_po'),
    ]

    operations = [
        migrations.CreateModel(
            name='priv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contrgrupp', verbose_name='Група')),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Група  - юзер',
                'verbose_name_plural': 'Група  - юзер',
                'db_table': 'priv',
            },
        ),
    ]
