# Generated by Django 4.2.7 on 2024-08-06 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_licenss_data_po'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=99, verbose_name='cod')),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contrgrupp', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Група  - юзер',
                'verbose_name_plural': 'Група  - юзер',
                'db_table': 'priv',
            },
        ),
    ]
