# Generated by Django 4.2.7 on 2024-06-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_priv'),
    ]

    operations = [
        migrations.AddField(
            model_name='priv',
            name='cod',
            field=models.CharField(default=1, verbose_name='cod'),
            preserve_default=False,
        ),
    ]
