# Generated by Django 4.2.7 on 2024-06-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='oper_mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=99, unique=True, verbose_name='guid')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Найменування')),
            ],
            options={
                'verbose_name': 'Операція',
                'verbose_name_plural': 'Операція',
                'db_table': 'oper',
            },
        ),
    ]
