# Generated by Django 4.2.7 on 2024-06-24 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=99, unique=True, verbose_name='guid')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'операції',
                'verbose_name_plural': 'операції',
                'db_table': 'operation',
            },
        ),
        migrations.CreateModel(
            name='tk_mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=99, unique=True, verbose_name='guid')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='technological_card.operations', verbose_name='Операції')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product_mod', verbose_name='ТМЦ')),
            ],
            options={
                'verbose_name': 'Технологічні карти',
                'verbose_name_plural': 'Технологічні карти',
                'db_table': 'technological_card',
            },
        ),
    ]
