# Generated by Django 4.2.7 on 2024-06-29 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
        ('technological_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tk_mod',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operation.oper_mod', verbose_name='Операції'),
        ),
        migrations.DeleteModel(
            name='operations',
        ),
    ]
